# Generated by Django 5.2.17 on 2026-10-06 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Talent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Artist or stage name.", max_length=120),
                ),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("dj", "DJ"),
                            ("vocalist", "Vocalist / singer"),
                            ("band", "Live band"),
                            ("dance", "Dance crew"),
                            ("host", "Host / MC"),
                            ("comedy", "Comedian"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True,
                        help_text="Genre or speciality, e.g. Afrobeats, Amapiano.",
                        max_length=120,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        help_text="Short biography, two or three sentences."
                    ),
                ),
                (
                    "previous_work",
                    models.TextField(
                        blank=True,
                        help_text="One item per line: residencies, headline shows, brands.",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        help_text="Main professional photo. Portrait works best.",
                        upload_to="talent/",
                    ),
                ),
                ("booking_available", models.BooleanField(default=True)),
                (
                    "travels",
                    models.BooleanField(
                        default=True,
                        help_text="Available for bookings outside the home city.",
                    ),
                ),
                ("spotify_url", models.URLField(blank=True)),
                ("apple_music_url", models.URLField(blank=True)),
                ("soundcloud_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("tiktok_url", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show on the homepage line-up."
                    ),
                ),
                (
                    "featured_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower numbers show first."
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        help_text="Home base.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="talent",
                        to="core.city",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "talent",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="TalentMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video (link)")],
                        default="photo",
                        max_length=5,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Required for photos. Optional thumbnail for videos.",
                        upload_to="media/%Y/%m/",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="Required for videos."),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "talent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="talent.talent",
                    ),
                ),
            ],
            options={
                "verbose_name": "photo or video",
                "verbose_name_plural": "photos and videos",
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
    ]
