# Generated by Django 4.2.9 on 2024-01-16 22:53

import custom_user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_adminuser_delete_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='adminuser',
            managers=[
                ('objects', custom_user.models.AdminUserManager()),
            ],
        ),
    ]
