# Generated by Django 5.2.17 on 2026-10-06 10:21

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("country", models.CharField(max_length=80)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "Euro (€)"),
                            ("NGN", "Naira (₦)"),
                            ("GBP", "Pound (£)"),
                            ("USD", "US dollar ($)"),
                            ("GHS", "Cedi (₵)"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        help_text="For example Europe/Madrid or Africa/Lagos.",
                        max_length=64,
                        validators=[apps.core.models.validate_timezone],
                    ),
                ),
                (
                    "ticket_provider",
                    models.CharField(
                        blank=True,
                        help_text="Default ticket partner for this city, e.g. Fourvenues or Tix.africa.",
                        max_length=80,
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="Shown on the site for this city, in international format.",
                        max_length=32,
                    ),
                ),
                ("instagram_url", models.URLField(blank=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to hide the city and everything in it from the site.",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "cities",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tickets", "Events and tickets"),
                            ("talent", "Talent bookings"),
                            ("collaboration", "Collaborations"),
                            ("shop", "Shop"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Events, talent and culture from Valencia to Lagos.",
                        max_length=200,
                    ),
                ),
                (
                    "about",
                    models.TextField(
                        blank=True,
                        help_text="Company biography for the Contact Us page.",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Receives contact form messages.",
                        max_length=254,
                    ),
                ),
                (
                    "booking_email",
                    models.EmailField(
                        blank=True,
                        help_text="Receives talent booking enquiries. Falls back to the contact email.",
                        max_length=254,
                    ),
                ),
                ("instagram_url", models.URLField(blank=True)),
                ("tiktok_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                (
                    "show_powered_by",
                    models.BooleanField(
                        default=True,
                        help_text="Show “Powered by SME Analytica” in the footer.",
                    ),
                ),
            ],
            options={
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
            },
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "map_url",
                    models.URLField(
                        blank=True, help_text="Google Maps or Apple Maps link."
                    ),
                ),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venues",
                        to="core.city",
                    ),
                ),
            ],
            options={
                "ordering": ("city", "name"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("city", "slug"), name="unique_venue_slug_per_city"
                    )
                ],
            },
        ),
    ]
