# Generated by Django 5.2.17 on 2026-10-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="currency",
            field=models.CharField(
                choices=[
                    ("EUR", "Euro (€)"),
                    ("NGN", "Naira (₦)"),
                    ("GBP", "Pound (£)"),
                    ("USD", "US dollar ($)"),
                    ("GHS", "Cedi (₵)"),
                    ("KES", "Kenyan shilling (KSh)"),
                    ("ZAR", "Rand (R)"),
                    ("XOF", "West African CFA franc (CFA)"),
                    ("MAD", "Moroccan dirham (DH)"),
                    ("EGP", "Egyptian pound (E£)"),
                    ("AED", "UAE dirham (AED)"),
                    ("CAD", "Canadian dollar (C$)"),
                ],
                max_length=3,
            ),
        ),
    ]
