# Generated by Django 5.2.17 on 2026-10-06 10:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("talent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("club", "Club night"),
                            ("live", "Live show"),
                            ("day", "Day party"),
                            ("festival", "Festival"),
                            ("talk", "Talk / mixer"),
                            ("private", "Private event"),
                        ],
                        default="club",
                        max_length=20,
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(
                        help_text="Doors open. Entered in the event city's local time."
                    ),
                ),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        help_text="Artwork or poster. Square or portrait.",
                        upload_to="events/",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="One line for the homepage, e.g. “Log drums, salt air, an early finish.”",
                        max_length=160,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "lineup_extra",
                    models.CharField(
                        blank=True,
                        help_text="Other names, comma separated, e.g. “Special guest”.",
                        max_length=255,
                    ),
                ),
                (
                    "music_style",
                    models.CharField(
                        choices=[
                            ("afrobeats", "Afrobeats"),
                            ("amapiano", "Amapiano"),
                            ("highlife", "Highlife"),
                            ("mixed", "Mixed"),
                        ],
                        default="afrobeats",
                        max_length=20,
                    ),
                ),
                (
                    "bpm",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Tempo for the homepage record player.",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(200)],
                    ),
                ),
                (
                    "ticket_url",
                    models.URLField(
                        blank=True,
                        help_text="Fourvenues, Tix.africa or other ticket page.",
                    ),
                ),
                (
                    "ticket_provider",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use the city's default.",
                        max_length=80,
                    ),
                ),
                (
                    "price_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="0 for free entry. Leave blank if not announced.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("sold_out", models.BooleanField(default=False)),
                (
                    "sold_percent",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Optional. Shows a “% sold” bar.",
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "age_restriction",
                    models.CharField(blank=True, default="18+", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Put it on the homepage record player."
                    ),
                ),
                (
                    "featured_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower numbers show first."
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="core.city",
                    ),
                ),
                (
                    "lineup",
                    models.ManyToManyField(
                        blank=True,
                        help_text="HOY talent playing.",
                        related_name="events",
                        to="talent.talent",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="core.venue",
                    ),
                ),
            ],
            options={
                "ordering": ("starts_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "starts_at"],
                        name="events_even_status_5c3d55_idx",
                    ),
                    models.Index(
                        fields=["city", "starts_at"],
                        name="events_even_city_id_199402_idx",
                    ),
                ],
            },
        ),
    ]
