# Generated by Django 5.2.17 on 2026-10-06 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "material",
                    models.CharField(
                        blank=True, help_text="e.g. 240 gsm cotton", max_length=120
                    ),
                ),
                (
                    "fit",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Boxy, Relaxed, One size",
                        max_length=60,
                    ),
                ),
                ("image", models.ImageField(upload_to="shop/")),
                ("is_published", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="shop/")),
                ("alt", models.CharField(blank=True, max_length=160)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "checkout_url",
                    models.URLField(
                        blank=True,
                        help_text="Stripe Payment Link (EUR) or Paystack page (NGN) until the native cart exists.",
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_prices",
                        to="core.city",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "ordering": ("city__order",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "city"), name="unique_price_per_city"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Size or variant, e.g. S, M, L, One size",
                        max_length=40,
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=60)),
                (
                    "stock",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Leave blank if you do not track stock.",
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "label"),
                        name="unique_variant_label_per_product",
                    )
                ],
            },
        ),
    ]
