# Generated by Django 5.2.17 on 2026-10-06 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        help_text="Leave blank to use the first photo.",
                        upload_to="gallery/covers/",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="albums",
                        to="core.city",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to show this album on the event page too.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="albums",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "-date", "-id"),
            },
        ),
        migrations.CreateModel(
            name="AlbumItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video (link)")],
                        default="photo",
                        max_length=5,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Required for photos. Optional thumbnail for videos.",
                        upload_to="media/%Y/%m/",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, help_text="Required for videos."),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="gallery.album",
                    ),
                ),
            ],
            options={
                "verbose_name": "photo or video",
                "verbose_name_plural": "photos and videos",
                "ordering": ("order", "id"),
                "abstract": False,
            },
        ),
    ]
