# Generated by Django 5.0 on 2023-12-29 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published_about', models.BooleanField(default=True, help_text='Check if the about entry is published')),
            ],
            options={
                'verbose_name_plural': 'Abouts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Check if the contact entry is valid')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='homepage/')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('content', models.TextField()),
                ('event_date', models.DateTimeField(help_text='Date and time of the event')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Check if the event is currently active')),
            ],
            options={
                'verbose_name_plural': 'Home Pages',
                'ordering': ('-event_date',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='events/')),
                ('event_date', models.DateTimeField(help_text='Date and time of the event')),
                ('is_published_event', models.BooleanField(default=True, help_text='Check if the event entry is published')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.homepage')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ('-event_date',),
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='blog_posts/')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, help_text='Check if the blog post is published')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.homepage')),
            ],
            options={
                'verbose_name_plural': 'Blog Posts',
                'ordering': ('-created_at',),
            },
        ),
    ]
