# Generated by Django 5.0 on 2024-01-03 22:01

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webgel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Cube'), ('2', 'Sphere'), ('3', 'Torus'), ('4', 'Cylinder'), ('5', 'Plane'), ('6', 'Heart'), ('7', 'Dodecahedron'), ('8', 'Octahedron'), ('9', 'Icosahedron'), ('10', 'Tetrahedron'), ('11', 'Ring'), ('12', 'Knot'), ('13', 'Polyhedron'), ('14', 'TorusKnot'), ('15', 'Stars')], max_length=3)),
                ('color', models.CharField(help_text=builtins.hex, max_length=7)),
            ],
        ),
    ]
