# Generated by Django 4.2.9 on 2024-01-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=None, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.organizer'),
        ),
    ]
