# Generated by Django 4.2.9 on 2024-01-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_event_image_alter_event_organizer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='description',
        ),
    ]
