# Generated by Django 4.2.9 on 2024-01-17 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_organizer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/collaborators'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(default='HOY', on_delete=django.db.models.deletion.CASCADE, to='core.organizer'),
        ),
    ]
