# Generated by Django 4.2.9 on 2024-01-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='home_page',
            field=models.BooleanField(default=False, help_text='Check if the event is for the homepage'),
        ),
    ]
