# Generated by Django 4.2.9 on 2024-01-17 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_event_home_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(help_text='Date and time of the event')),
                ('is_active', models.BooleanField(default=True, help_text='Check if the event is currently active')),
            ],
            options={
                'verbose_name_plural': 'Home Pages',
                'ordering': ('-event_date',),
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='home_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.homepage'),
        ),
    ]
