# Generated by Django 4.2.9 on 2024-01-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_event_event_date_alter_event_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='name',
            new_name='address',
        ),
    ]
