# Generated by Django 4.2.9 on 2024-01-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_name_venue_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_time',
        ),
    ]
