# Generated by Django 4.2.9 on 2024-01-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_event_collaborator_event_sponsor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='collaborator',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='event',
            name='collaborator',
            field=models.ManyToManyField(blank=True, related_name='events', to='core.collaborator'),
        ),
        migrations.AddField(
            model_name='event',
            name='sponsor',
            field=models.ManyToManyField(blank=True, related_name='event_sponsors', to='core.sponsor'),
        ),
    ]
