# Generated by Django 4.2.10 on 2024-04-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_blogpost_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='events_attending',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='event',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='collaborator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='session',
            name='event',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='events',
        ),
        migrations.DeleteModel(
            name='Webgel',
        ),
        migrations.RemoveField(
            model_name='event',
            name='collaborator',
        ),
        migrations.RemoveField(
            model_name='event',
            name='home_page',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='event',
            name='event_qrcode',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
        migrations.DeleteModel(
            name='Attendee',
        ),
        migrations.DeleteModel(
            name='Collaborator',
        ),
        migrations.DeleteModel(
            name='Homepage',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
    ]
