# Generated by Django 4.2.10 on 2024-04-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_attendee_events_attending_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='venue',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_qrcode',
            field=models.ImageField(blank=True, upload_to='event_qrcodes/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='€', max_digits=10),
        ),
    ]
