# Generated by Django 4.2.10 on 2024-04-10 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_event_venue_alter_event_event_qrcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField(help_text='Date and time of the event')),
                ('is_active', models.BooleanField(default=True, help_text='Check if the event is currently active')),
            ],
            options={
                'verbose_name_plural': 'Home Pages',
                'ordering': ('-event_date',),
            },
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.AlterModelOptions(
            name='organizer',
            options={'verbose_name': 'Organizer', 'verbose_name_plural': 'Organizers'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_qrcode',
        ),
        migrations.RemoveField(
            model_name='event',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organizer'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, help_text='Date of the event', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='name',
            field=models.CharField(help_text='Name of the organizer', max_length=100, unique=True),
        ),
    ]
