# Generated by Django 4.2.10 on 2024-04-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_index_delete_venue_alter_organizer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='event_qrcodes/'),
        ),
    ]
