# Generated by Django 5.2.17 on 2026-10-06 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("talent", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In progress"),
                            ("waiting", "Waiting on client"),
                            ("won", "Confirmed / won"),
                            ("lost", "Declined / lost"),
                            ("closed", "Closed"),
                            ("spam", "Spam"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=12,
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Only visible to the HOY team."
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("privacy_accepted", models.BooleanField(default=False)),
                ("client_name", models.CharField(max_length=120)),
                ("company", models.CharField(blank=True, max_length=120)),
                ("event_date", models.DateField()),
                ("event_location", models.CharField(max_length=200)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("concert", "Concert / show"),
                            ("club", "Club night"),
                            ("private", "Private party"),
                            ("corporate", "Corporate / brand"),
                            ("wedding", "Wedding"),
                            ("festival", "Festival"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "expected_audience",
                    models.CharField(
                        choices=[
                            ("lt100", "Under 100"),
                            ("100-300", "100 to 300"),
                            ("300-1000", "300 to 1,000"),
                            ("gt1000", "Over 1,000"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.city",
                    ),
                ),
                (
                    "talent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enquiries",
                        to="talent.talent",
                    ),
                ),
            ],
            options={
                "verbose_name": "booking enquiry",
                "verbose_name_plural": "booking enquiries",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In progress"),
                            ("waiting", "Waiting on client"),
                            ("won", "Confirmed / won"),
                            ("lost", "Declined / lost"),
                            ("closed", "Closed"),
                            ("spam", "Spam"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=12,
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True, help_text="Only visible to the HOY team."
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("privacy_accepted", models.BooleanField(default=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General enquiry"),
                            ("talent", "Talent booking"),
                            ("collaboration", "Event collaboration"),
                            ("business", "Business enquiry"),
                            ("press", "Media / press"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("subject", models.CharField(blank=True, max_length=160)),
                ("message", models.TextField()),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "contact message",
                "verbose_name_plural": "contact messages",
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
